[package]
name = "markdown2html-converter"
version = "1.1.0"
authors = ["Magic Len <len@magiclen.org>"]
edition = "2018"
repository = "https://github.com/magiclen/markdown2html-converter"
homepage = "https://magiclen.org/markdown2html-converter"
keywords = ["markdown", "html", "MathJax", "LaTeX", "highlight"]
categories = ["command-line-utilities"]
description= "A tool for converting a Markdown file to a single HTML file with built-in CSS and JS."
readme = "README.md"
license = "MIT"
include = ["src/**/*", "Cargo.toml"]

[badges.travis-ci]
repository = "magiclen/markdown2html-converter"
branch = "master"

[profile.release]
panic = "abort"

[dependencies]
clap = "2.32.0"
concat-with = "0.2"
terminal_size = "0.1"

lazy-static-include = "3"
html-minifier = "2"
comrak = "0.7"
html-escape = "0.2"
slash-formatter = "3"

[dependencies.path-absolutize]
version = "3"
features = ["lazy_static_cache"]